# Generated by Django 4.0.3 on 2022-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
