# Generated by Django 4.0.3 on 2022-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='usertype',
            field=models.BooleanField(default=False),
        ),
    ]
