# Generated by Django 4.0.3 on 2022-03-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_products_pimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='catid',
            new_name='cId',
        ),
    ]
