# Generated by Django 4.0.3 on 2022-04-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_users_usertype'),
        ('product', '0005_alter_products_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='uId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.users'),
        ),
    ]
